### ISSUE TITLE
Farbschema RW: Siegel broken

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Blog#4]
Bei dem Farbschema RW ist das falsche Siegel in Verwendung

**Comment by cassandre** [comment]
Hoppla, stimmt. Ist jetzt in dev gefixt. Ich warte mit einem Merge für eine neue Version noch ein bisschen – da kommen bestimmt noch mehr Tickets, wenn du schon mal beim Testen bist. ;-)
