### ISSUE TITLE
Links im Footer

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Blog#5]
Würde ich ändern: Die Leute brauchen für ihre eigenen Blogs eigene Kontaktdaten.
Wenn wir das so drin lassen, werden die von selbst nichts öndern - die Erfahrung haben wir ja bei den Websites

**Comment by xwolfde** [comment]
ggf. aber folgende Links rein als Default ins Menü unten:

 Nutzungsbedingungen, https://blogs.fau.de/nutzungsbedingungen/
 Hilfe, https://blogs.fau.de/hilfe
 Blogübersicht, https://blogs.fau.de/?a=bloguebersicht

**Comment by cassandre** [comment]
Links erledigt, Kontaktdaten haben noch einen Bug.
